export default {
  $ieActionBtn: 36,
  $ieRegularPadding: 8,
  $ieSmallPadding: 4,
  $ieExtraPadding: 16,
  $ieLargePadding: 24,
  $ieSmallMargin: 4,
  $ieRegularMargin: 8,
  $ieLargeMargin: 16,
  $ieXLargeMargin: 24,
  $ieElementWidth: '90%',
  $ieSmallRadius: 5,
  $ieRegularRadius: 10,
  $ieLargeRadius: 20,
  $ieMaxRadius: 35,
  $btnDimension: 70,
  $floatingBtn: 50,
  $ieFlexGap: 8,
  $ieFlexGapLarge: 16,
  $ieFlexGapXLarge: 32,
  $ieLargeFont: 20,
  $ieSmallFont: 12,
  $ieRegularFont: 16,
  $ieMediumFont: 14,
  $ieTitleFont: 24,
  $navDimension: '10%',
  $ieRowAvatar: 75,
  $ieColumnAvatar: 150,
  $ieMenuMaxHeight: 75,
  $ieMenuBottomSpace: 25,
  $ieMenuSpace: 100,
  $ieSmallBorder: 1,
  $ieRegularBorder: 2,
  $ieLargeBorder: 4,
  $ieXLargeBorder: 6,

  // Input elements specific
  $startIconSize: 20,
  $alertIconSize: 72,
  $ieRegularHeight: 48,
  $ieLargeHeight: 56,
  $ieXLargeHeight: 64,
  $ieMaxHeight: 64,
  $ieMinHeight: 48,
};
