export default {
  $ieRegularHeight: 48,
  $ieLargeHeight: 56,
  $ieXLargeHeight: 64,
  $ieMaxHeight: 64,
  $ieMinHeight: 48,
  $ieRegularPadding: 8,
  $ieSmallPadding: 4,
  $ieExtraPadding: 16,
  $ieLargePadding: 24,
  $ieSmallMargin: 4,
  $ieRegularMargin: 8,
  $ieExtraMargin: 16,
  $ieElementWidth: '90%',
  $ieSmallRadius: 5,
  $ieRegularRadius: 10,
  $ieLargeRadius: 20,
  $btnDimension: 70,
  $navDimension: '10%',
  $ieFlexGap: 8,
  $ieFlexGapLarge: 16,
  $ieLargeFont: 20,
  $ieSmallFont: 12,
  $ieRegularFont: 16,
  $ieMediumFont: 14,
  $ieTitleFont: 32,
};
